### ISSUE TITLE
Does not work with Azure Functions v1

### ISSUE THREAD

**Issue by douglasware** [Azure/AppConfiguration-DotnetProvider#194] opened 2020-08-06 20:08 UTC
To reproduce, create a v1 function app, pull in any of the release packages or the current preview and attempt to call AddAzureAppConfiguration
e.g.
builder = new ConfigurationBuilder();
_config = builder.AddAzureAppConfiguration(appServiceConnection).Build();

Result is - Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  Source=System.Diagnostics.DiagnosticSource
  StackTrace:
   at System.Diagnostics.Activity.get_Id()
   at System.Diagnostics.Activity.Stop()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.<CallWithRequestTracing>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<CallWithRequestTracing>d__23.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<LoadAll>d__15.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at ConfigServiceLib.AppConfig.GetConfigValue(String appServiceConnection, String item) in C:\Users\FG341VF\source\repos\NewtestAppConfig\NewtestAppConfig\AppConfig.cs:line 16
   at NewtestAppConfig.Function1.Run(TimerInfo myTimer, TraceWriter log) in C:\Users\FG341VF\source\repos\NewtestAppConfig\NewtestAppConfig\Function1.cs:line 14
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__9.MoveNext()

**Comment by abhilasharora** [comment] 2020-08-06 20:21
@douglasware To diagnose the issue, could you share the following details?
1. List of packages used in your `csproj` file
2. Version of `System.Memory.dll` is present in the `bin` directory in your project
3. Versions of `System.Memory` available in the Nuget cache directory typically at `C:\Users\{userName}\.nuget`

**Comment by douglasware** [comment] 2020-08-06 21:08
1)  <PackageReference Include="Azure.Storage.Blobs" Version="12.2.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.0.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="3.0.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />

2) 4.6.27617.2
3) 4.6.28619.1, 4.6.27617.2, 4.6.26606.5, 4.6.26515.6

Note: the error is observable locally and in deployed Azure Functions and can be reproduced simply by following the tutorial at docs.microsoft.com with a v1 Function app.

**Comment by douglasware** [comment] 2020-08-11 17:54
@abhilasharora should I open an official support ticket for this?

**Comment by abhilasharora** [comment] 2020-08-11 18:06
@douglasware Apologies for the delay here. I can reproduce the issue. I'm looking into a possible workaround so the package could be used with v1 runtime of Azure Functions.

**Comment by abhilasharora** [comment] 2020-08-12 16:02
@douglasware The following code snippet can be included in an Azure Functions v1 application to address the assembly resolution issues at runtime when using the App Configuration package. This method needs to be invoked in the function startup code or the constructor. It registers event handlers to ensure that the _appropriate_ versions of the required assemblies needed for App Configuration are loaded at runtime.

Please note that version `1.x` of Azure Functions runtime is in [maintenance mode](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions). The recommended approach is to upgrade existing applications to `.NET Core` and a newer version of the runtime.

```` csharp
public static void ConfigureBindingRedirectsForAppConfiguration()
{
    var bindingRedirects = new Dictionary<string, string>
    {
        { "System.Memory", "4.0.1.1" },
        { "System.Runtime.CompilerServices.Unsafe", "4.0.5.0" },
        { "System.Buffers", "4.0.3.0" },
        { "System.Numerics.Vectors", "4.1.4.0" }
    };

    foreach (var redirect in bindingRedirects)
    {
        AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
        {
            var requestedAssembly = new AssemblyName(args.Name);
            if (requestedAssembly.Name == redirect.Key)
            {
                requestedAssembly.Version = new Version(redirect.Value);
                return Assembly.Load(requestedAssembly);
            }
            return null;
        };
    }
}
````

**Comment by douglasware** [comment] 2020-08-13 14:04
Thanks Abhilash!
We will give this a try and let you know. 

I am well aware that v1 is in maintenance mode. We use v3 when we can.

I'm part of a large customer and our user base is hundreds of thousands of people and we have a very large global footprint. We are mostly building on .NET Standard because we have significant edge cases still requiring .NET Framework and will be in that mode for the foreseeable future. So, compatibility with Functions v1 for the configuration system is pretty important as configuration concerns are global. If there was not a good workaround for this issue, we probably would stick with what we have previously built in house and forgo the use of the App Config Service.

This is why I ask if we should also open a ticket wrt to Functions. Microsoft tends to do things for us that they might not otherwise do if we ask nicely. ;)

**Comment by timhuang77** [comment] 2020-10-12 04:58
@abhilasharora I'm having this exact issue with Azure Functions v1 runtime and can confirm the workaround is working, do you know what might be the root cause?

However, if I were to use Azure.Identity v1.2.3 and Microsoft.Extensions.Configuration.AzureAppConfiguration v4.0.0, Azure Core 1.0.1 is the one causing the error:

```
System.IO.FileNotFoundException
HResult=0x80070002
Message=Could not load file or assembly 'Azure.Core, Version=1.0.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.
```

BindingRedirects were used to redirect Azure.Core to use 1.4.1.0 instead of 1.0.1.0, but to no avail. Also tried adding the package directly to the library that we were developing, also to no avail.

I suspect there is compatibility issue between AppConfiguration extension and Runtime v1? Or possibly compatibility issue between Azure.Identity v1.2.3 and AppConfiguration extension (which uses Azure.Core v.1.4.1, where AppConfiguration uses v1.0.1 - it refuses to look for 1.4.1 no matter what binding redirects are thrown at it)?

**Comment by abhilasharora** [comment] 2020-10-13 01:09
@timhuang77 I believe the root cause is related to the usage of other assemblies that reference an older version of these assemblies in the .NET Framework application. For the error message in your post, adding the following additional binding redirect should help. In case it isn't working, I'd suggest cleaning up the temporary project files, clearing the NuGet cache directory, or using it in a new project or on a different development machine to ensure it isn't caused due to stale state.

`{ "Azure.Core", "1.4.1.0" }`

**Comment by timhuang77** [comment] 2020-10-15 06:45
I see. I guess my question is why would BindingRedirects have no effect on these assemblies?

Assembly conflicts are common, and they're usually resolved with bindingRedirects. But in this case, no matter how it is redirected, it seems to reference older assemblies nonetheless.

For example, in the previous case, `System.Memory 4.0.1.0` should be redirected to `4.0.1.1` but no matter how the conflict is resolved, either 1) Direct-Add to the root-project or 2) BindingRedirect, neither attempts work.

Regardless, the runtime approach to redirecting these assemblies have worked for me.

**Comment by abhilasharora** [comment] 2020-10-15 16:55
@timhuang77 Yes, that's the expected behavior since Azure Functions do not support binding redirects. There are multiple issues in the Azure Functions repository where this has been reported by other users. Here is a [link](https://github.com/Azure/Azure-Functions/issues?q=is%3Aissue+%22binding+redirect%22+in%3Atitle+) to some of these.

**Closed** 2021-03-21 20:49 UTC
Labels: wontfix
