### ISSUE TITLE
Unawaited refresh tasks

### ISSUE THREAD

**Issue by stevendarby** [Azure/AppConfiguration-DotnetProvider#424] opened 2023-05-26 15:56 UTC
Hello,

We're getting occasional exceptions in our ASP.NET Core web app, which appear to be in this class of problem: https://github.com/dotnet/aspnetcore/issues/42040

As a result we are trying to locate anything in our middleware leading up to the exception which could result in concurrent HttpContext access. One way this can come about (as discussed in some of the issues linked from above) is by not awaiting a Task. I came across this...

https://github.com/Azure/AppConfiguration-DotnetProvider/blob/9a76d2a1b43d137e139e329a575eee09641e51d3/src/Microsoft.Azure.AppConfiguration.AspNetCore/AzureAppConfigurationRefreshMiddleware.cs#L27-L30

This could well be red herring and I've nothing to show this is definitely our problem, but I wanted to raise it anyway as unawaited Tasks are a bit of a code smell anyway.

Do you think it's safe to do this?

**Comment by amerjusupovic** [comment] 2023-06-05 19:45
Hi @stevendarby, we don't await `TryRefreshAsync` because we don't want to block or slow down any request that triggers a refresh. The provider code does protect against any potential issues with running `TryRefreshAsync` asynchronously, so it's safe to do it this way.

**Comment by stevendarby** [comment] 2023-06-05 20:18
From what I could tell, it protects against other concurrent refreshers but it doesn't protect against other code running concurrently, e.g. the next middleware, which we may have progressed to given yours is unawaited. 

We know from the linked issues that application insights telemetry initialisers may access HttpContext and so your log statements when application insights is being used could lead to concurrent access of HttpContext. We have however ensured we lock on HttpContext in telemetry initialisers to avoid this, but this serves to highlight a non-obvious way your code might not be safe to run concurrently when it exists among other code and other libraries. 

I guess I will need to get into the meat of what the refreshers do to see if HttpContext is actually involved but from reading through those linked issues and comments from @davidfowl, @Tratcher et al, my impression is that parallel execution, unawaited tasks etc. during a request are generally recommended against.

**Comment by Tratcher** [comment] 2023-06-05 22:29
Why is refresh even happening in middleware? It doesn't seem to require any request input(?), and it gets triggered way too often (e.g. 10,000 RPS).

This seems like a good candidate for a BackgroundService.
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs#L13

It would be simpler too, you wouldn't have to worry about concurrent executions.

**Comment by stevendarby** [comment] 2023-06-06 19:30
@amerjusupovic re: whether it accesses HttpContext, you probably won't find a direct reference but I would take a look at the SqlClient issue that's linked in one of my comments.

The issue came from unawaited diagnostics; if application insights was also being used in the app, then handling of those diagnostics could involve HttpContext. And because that was happening in parallel with other application code, concurrent HttpContext could occur.

I believe this closely parallels what is happening in your middleware. The unawaited refresher code involves logging and diagnostics. In isolation, this is fine, but when application insights is being used, potential concurrent HttpContext access is introduced. If this summary sounds wrong to anyone, please feel free to correct, as I'm only just getting my head around it myself.

So I think the advice is generally to always await tasks to play nicely with other libraries, particularly application insights (there may be other examples).

I like the background service idea.

**Comment by amerjusupovic** [comment] 2023-06-06 21:33
@stevendarby I see, from the way I understood the issue I was hoping we could point to a specific example of how the task accesses HttpContext. Looking at some of the other issues linked in the one you sent, I can see that they look really similar to this case, so I also think it could be what's happening here.

Regardless, if the background service solution lets us keep the same functionality of not blocking/slowing down requests then I think it's a good idea as well. As mentioned, it leaves less to worry about. 

Also, is there an easy way to reproduce this issue? Am I understanding correctly that just having application insights enabled could cause a null reference while the application is running?

**Comment by stevendarby** [comment] 2023-07-13 15:17
@amerjusupovic great to see. The solution took me a little reading up to understand, but looks good! Out of interest, do you have a rough ballpark for when this might get released? Will just keep an eye on it if not.

**Comment by amerjusupovic** [comment] 2023-07-13 15:38
@stevendarby we don't have an exact plan at the moment, but we're trying to get this released sometime next week.

**Comment by avanigupta** [comment] 2023-08-23 18:16
Fix has been released with [6.1.0](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/6.1.0) package version.

**Closed by avanigupta** 2023-08-23 18:16 UTC
