### ISSUE TITLE
App Configuration outage shouldn't block application's startup when optional is true

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration-DotnetProvider#370] opened 2022-12-10 14:48 UTC
This is a follow-up question for https://github.com/Azure/AppConfiguration/issues/699

As region replication is not generally available yet, we are following [Primary Store + Secondary Store pattern](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-disaster-recovery?tabs=core2x) for high availability. 

But found App Configuration outage may block the application's startup even when optional is true

[Unhandled exceptions cause application crash which can result in crash loops as orchestrators attempt to restart the application](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/main/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationProvider.cs#L137)

In this case, any AAC Primary Store or AAC Secondary Store outage would block application startup, which doesn't achieve the 
high availability purpose. 
App Configuration outage shouldn't block the application's startup when optional is true

**Comment by avanigupta** [comment] 2022-12-12 20:24
Hello @lissdy, the comment you linked above is applicable only when optional is not true. This is because `LoadAll` method swallows exceptions related to AppConfig errors when optional is true ([code](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/67a31de862387279586eff551e0b94f65ec35022/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationProvider.cs#L339)).

So any App Configuration outage will not block the application's startup when optional is true.

**Comment by lissdy** [comment] 2022-12-13 02:48
@avanigupta , appreciate your reply! Actually, I don't have a good way to emulate App Configuration outage. 
I tried to update the app configuration endpoint from https://XXX.azconfig.io to https://XXX.azconfig.test, and found the application startup would be blocked even when the optional is true.

But I realized to emulate App Configuration outage,  I should just dummy the App Configuration Name, update endpoint from https://XXX.azconfig.io to https://dummy.azconfig.io, and it works as expected.

**Comment by lissdy** [comment] 2022-12-14 02:59
Hey @avanigupta , sorry to reopen the issue. May I know is possible to swallow `Azure.Identity.AuthenticationFailedException`  when Optional is true?
Otherwise, when trying to connect App Configuration via Managed Identity, any authentication exception may block the application startup as well. Thanks

**Comment by avanigupta** [comment] 2022-12-14 19:06
The optional flag is meant to protect application startup from AppConfig related errors/outages. If there is an authentication error like 401 or 403, it will bubble up as `RequestFailedException` and we will swallow it during startup. This behavior is the same, regardless of the type of credentials used.

In what scenario do you see `Azure.Identity.AuthenticationFailedException`?

**Comment by avanigupta** [comment] 2023-03-15 19:55
Hi @lissdy, please let me know if you need further assistance with this. Closing for now because this behavior is by design.

**Closed by avanigupta** 2023-03-15 19:55 UTC
